name: adt_annotation
description: Annotations and helper stuff for algebraic data types code generator.
version: 0.3.0+1
homepage: https://github.com/vr19860507/adt_annotation

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  meta: ^1.0.0
  collection: ^1.0.0

dev_dependencies:
  strict_analyzer: ^0.4.0



