name: adt_annotation
description: Annotations and helper stuff for algebraic data types code generator.
version: 0.1.0+1
homepage: https://github.com/vr19860507/adt_annotation

environment:
  sdk: ">=2.8.1 <3.0.0"

dependencies:
  meta: ^1.1.8
  collection: ^1.14.12

dev_dependencies:
  strict_analyzer: ^0.2.0



